### ISSUE TITLE
How can I inference the diffusion model?

### ISSUE THREAD

**Issue by 0oOMiNGOo0** [HReynaud/EchoDiffusion#5]
Hello, I'm trying to train and inference the model.
However, in README.me, there are only how to train model and evaluation.
I don't need to get the score, I just want to see the inference result.
What should I do?

**Comment by HReynaud** [comment]
Hi !
You can use the [generate_dataset.py](https://github.com/HReynaud/EchoDiffusion/blob/dbf786ac9c4a93ba4c390cdf339bad249cae12bd/diffusion/generate_samples/generate_dataset.py#L153) script, which wil generate as many samples as you have EF scores in the ef_list file.
There is no script to generate one single sample, but making one from `generate_dataset.py` should be easy.
Also, you could clone the gradio demo [here](https://huggingface.co/spaces/HReynaud/EchoDiffusionDemo) to have something more interactive.
I hope this helps !
